// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using plant_manager.Data;

#nullable disable

namespace plant_manager.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260518153034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("plant_manager.Data.Models.ActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("CareActionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PerformedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CareActionId");

                    b.HasIndex("PlantId");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("plant_manager.Data.Models.ActionLogResource", b =>
                {
                    b.Property<int>("ActionLogId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("ActionLogId", "ActionResourceId");

                    b.HasIndex("ActionResourceId");

                    b.ToTable("ActionLogResources");
                });

            modelBuilder.Entity("plant_manager.Data.Models.ActionResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ActionResources");
                });

            modelBuilder.Entity("plant_manager.Data.Models.CareAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CareActions");
                });

            modelBuilder.Entity("plant_manager.Data.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxonId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TaxonId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("plant_manager.Data.Models.PlantCareSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CareActionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EveryDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CareActionId");

                    b.HasIndex("PlantId", "CareActionId")
                        .IsUnique();

                    b.ToTable("PlantCareSchedules");
                });

            modelBuilder.Entity("plant_manager.Data.Models.PlantFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlantFlagDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ResolvedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlantFlagDefinitionId");

                    b.HasIndex("PlantId", "PlantFlagDefinitionId", "ResolvedOn");

                    b.ToTable("PlantFlags");
                });

            modelBuilder.Entity("plant_manager.Data.Models.PlantFlagDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PlantFlagDefinitions");
                });

            modelBuilder.Entity("plant_manager.Data.Models.PlantTaxon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Authority")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cultivar")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genus")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Variety")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlantTaxa");
                });

            modelBuilder.Entity("plant_manager.Data.Models.ActionLog", b =>
                {
                    b.HasOne("plant_manager.Data.Models.CareAction", "CareAction")
                        .WithMany("ActionLogs")
                        .HasForeignKey("CareActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("plant_manager.Data.Models.Plant", "Plant")
                        .WithMany("ActionLogs")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareAction");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("plant_manager.Data.Models.ActionLogResource", b =>
                {
                    b.HasOne("plant_manager.Data.Models.ActionLog", "ActionLog")
                        .WithMany("Resources")
                        .HasForeignKey("ActionLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("plant_manager.Data.Models.ActionResource", "ActionResource")
                        .WithMany("ActionLogResources")
                        .HasForeignKey("ActionResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActionLog");

                    b.Navigation("ActionResource");
                });

            modelBuilder.Entity("plant_manager.Data.Models.Plant", b =>
                {
                    b.HasOne("plant_manager.Data.Models.PlantTaxon", "Taxon")
                        .WithMany()
                        .HasForeignKey("TaxonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Taxon");
                });

            modelBuilder.Entity("plant_manager.Data.Models.PlantCareSchedule", b =>
                {
                    b.HasOne("plant_manager.Data.Models.CareAction", "CareAction")
                        .WithMany("PlantCareSchedules")
                        .HasForeignKey("CareActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("plant_manager.Data.Models.Plant", "Plant")
                        .WithMany("CareSchedules")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareAction");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("plant_manager.Data.Models.PlantFlag", b =>
                {
                    b.HasOne("plant_manager.Data.Models.PlantFlagDefinition", "Definition")
                        .WithMany("PlantFlags")
                        .HasForeignKey("PlantFlagDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("plant_manager.Data.Models.Plant", "Plant")
                        .WithMany("Flags")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("plant_manager.Data.Models.ActionLog", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("plant_manager.Data.Models.ActionResource", b =>
                {
                    b.Navigation("ActionLogResources");
                });

            modelBuilder.Entity("plant_manager.Data.Models.CareAction", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("PlantCareSchedules");
                });

            modelBuilder.Entity("plant_manager.Data.Models.Plant", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("CareSchedules");

                    b.Navigation("Flags");
                });

            modelBuilder.Entity("plant_manager.Data.Models.PlantFlagDefinition", b =>
                {
                    b.Navigation("PlantFlags");
                });
#pragma warning restore 612, 618
        }
    }
}
